image: gradle:jdk11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache --full-stacktrace assemble
  cache:
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache --full-stacktrace check
    - cat build/reports/jacoco/test/html/index.html
  cache:
    paths:
      - .gradle
      - build

bintray:
  only:
    - master
  stage: deploy
  script: gradle bintrayUpload
  cache:
    policy: pull
    paths:
      - .gradle
      - build

pages:
  only:
    - master
  stage: deploy
  script:
    - gradle globalJavadoc
    - mv build/docs/javadoc public
  artifacts:
    paths:
      - public
  cache:
    policy: pull
    paths:
      - build/docs/
